INSERT INTO random_comments VALUES ('Good ride, but too ex');
INSERT INTO random_comments VALUES ('Comfortable ride, driver was polite, would use again');
INSERT INTO random_comments VALUES ('Love it! The driver was very nice');
INSERT INTO random_comments VALUES ('Good way to carpool');
INSERT INTO random_comments VALUES ('The driver got here on time and was fast');
INSERT INTO random_comments VALUES ('Driver was understanding when I needed to rush');
INSERT INTO random_comments VALUES ('Good ride overall');
INSERT INTO random_comments VALUES ('Definitely will carpool again');
INSERT INTO random_comments VALUES ('It was good to carpool and save');
INSERT INTO random_comments VALUES ('Love it!');
INSERT INTO random_comments VALUES ('Driver handled my drunk friend well');
INSERT INTO random_comments VALUES ('Had a good ride');
INSERT INTO random_comments VALUES ('Driver as good as taxi uncle');
INSERT INTO random_comments VALUES ('Didnt expect much from carpooling but I wont mind using it again');
INSERT INTO random_comments VALUES ('App got me a ride fast!');
INSERT INTO random_comments VALUES ('Great way to avoid crowded MRT');
INSERT INTO random_comments VALUES ('Cheaper than taxi, didnt mind the pooling');
INSERT INTO random_comments VALUES ('Had a nice after-work nap');
INSERT INTO random_comments VALUES ('It was my first time trying and turns out it is not that bad');
INSERT INTO random_comments VALUES ('Had a nice convenient ride'); 
